# Generated by Django 5.2 on 2025-04-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comuna_region_cliente_comuna_comuna_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio_de_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=255)),
                ('tipo_de_cuenta', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='myapp.cliente')),
            ],
        ),
    ]
